version: '3.8'

services:
  web:
    build: .
    #image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=maudeInterface
      - MYSQL_PASSWORD=maudeInterface
      - MYSQL_DATABASE=maudeInterface
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: maudeInterface
      MYSQL_USER: maudeInterface
      MYSQL_PASSWORD: maudeInterface
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: